# configs/divide_conquer_config.yaml
# Configuration for Divide-and-Conquer model (awardWonBy relation)

model: "improved_divide_conquer"
llm_path: "Qwen/Qwen3-8B"
prompt_templates_file: "prompt_templates/question_prompts.csv"

# Model parameters
max_new_tokens: 32768
use_quantization: false
temperature: 0.2

# Few-shot learning (disabled to avoid interference)
few_shot: 0

# Data files
train_data_file: "data/train.jsonl"

# Divide-and-conquer specific configuration
use_divide_conquer: ["awardWonBy"]
max_query_attempts: 3

# Query decomposition settings
temporal_categories: ["1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s", "2020s"]
geographic_categories: ["American", "British", "German", "French", "Italian", "Japanese", "Canadian", "Chinese", "other"]

# Name validation settings
min_name_length: 2
max_name_length: 50
max_words_per_name: 4

# Logging configuration
save_logs: true
log_dir: "experiment_logs/divide_conquer"